language: nix

# sudo: false

# cache:
#   directories:
#     - /nix
#   timeout: 100000

git:
  depth: 1

env:
  global:
    - NIXPKGS_TESTS=yes
    - MATCHING_TESTS=yes
  matrix:
    - GHCVERSION=ghc802 STRICT=false TRACING=false
    - GHCVERSION=ghc802 STRICT=false TRACING=true
    - GHCVERSION=ghc822 STRICT=true  TRACING=false
    - GHCVERSION=ghc822 STRICT=true  TRACING=true
    - GHCVERSION=ghc843 STRICT=false TRACING=false
    - GHCVERSION=ghc843 STRICT=false TRACING=true
    - GHCVERSION=ghcjs

matrix:
  allow_failures:
    - env: GHCVERSION=ghcjs
  exclude:
    - env: GHCVERSION=ghc822 STRICT=false

script:
  - bash -xe build.sh

branches:
  only:
    - master
    - pending

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b0312b18473340459d3e
    on_success: change
    on_failure: always
    on_start: never
