language: nix

# sudo: false

# cache:
#   directories:
#     - /nix
#   timeout: 100000

git:
  depth: 1

env:
  global:
    - NIXPKGS_TESTS=yes
    - MATCHING_TESTS=yes
  matrix:
    - GHCVERSION=ghc802 STRICT=false TRACING=false
    - GHCVERSION=ghc802 STRICT=false TRACING=true
    - GHCVERSION=ghc822 STRICT=true  TRACING=false
    - GHCVERSION=ghc822 STRICT=true  TRACING=true
    - GHCVERSION=ghc842 STRICT=false TRACING=false
    - GHCVERSION=ghc842 STRICT=false TRACING=true
    - GHCVERSION=ghcjs

matrix:
  allow_failures:
    - env: GHCVERSION=ghcjs
  exclude:
    - env: GHCVERSION=ghc822 STRICT=false

script:
  - bash -xe build.sh
  - nix-shell --pure --run "cabal configure --enable-tests"
  - nix-shell --pure --run "cabal build"
  - nix-shell --pure --run "env ALL_TESTS=yes cabal test"

branches:
  only:
    - master
    - pending

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b0312b18473340459d3e
    on_success: change
    on_failure: always
    on_start: never
